version: "3"
services:
  ls:
    build: .
    image: club9822/ls-server:1.0.0
    expose:
      - 8080
      - 8001
      - 8002
      - 8003
    ports:
      - "80:8080"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"