version: '3'
name: minio
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "6000:9000"
      - "6001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: pass1234@
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}