version: '3'
name: postgres
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass1234@
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres  
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:4.24"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pass1234@
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres  
    ports:
      - "5433:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
    
networks:
  postgres:
    driver: bridge    